### ISSUE TITLE
get routes does not display multipath routes for fattree4 example

### ISSUE THREAD

**Issue by agember** [batfish/batfish#1556]
As an example, edge-7 should be able to go through either aggregation switch in its pod to reach edge-10 (70.0.10.0/24), but get routes includes only one route via aggregation-4:
`edge-7 vrf:default net:70.0.10.0/24 nhip:10.0.1.0 nhint:dynamic nhnode:aggregation-4 admin:20 cost:0 tag:none prot:bgp`
edge-7 should compute multiple routes, because the `router bgp` configuration on edge-7 contains `bgp bestpath as-path multipath-relax`

**Comment by dhalperi** [comment]
@progwriter might be able to help diagnose this.

**Comment by dhalperi** [comment]
Hi @agember -- I somehow ended up looking at the code affected in #1582 and I ended up getting very confused.

How did you determine that this is a bug, and the behavior described in your issue is correct, namely this part?

> edge-7 should compute multiple routes, because the router bgp configuration on edge-7 contains `bgp bestpath as-path multipath-relax`

From what I can see of the cisco docs, you are required to specify `maximum-paths N` for `N>1` in order to enable ECMP. And if you don't, `bgp bestpath as-path multipath-relax` alone won't enable it.

**Comment by agember** [comment]
@dhalperi Sorry for my delayed response; I had not noticed your comment. My bug reported was based on reading community discussions online. After some further reading and running a simulation in Cisco Virtual Internet Routing Lab, I agree that you must also specify `maximum-paths N` for `N > 1` in order for `bgp bestpath as-path multipath-relax` to matter. Sorry for the faulty bug report.
