### ISSUE TITLE
Problem parsing snmp community name with special characters in it

### ISSUE THREAD

**Issue by jlmcgraw** [batfish/batfish#1882]
Using a Cisco IOS configuration, having an snmp community name with special characters  in it (which is valid configuration, at least for this software) causes the line not to parse properly, leading to the ACL being considered as undefined and unused

input configuration:
----------------------------------------------------------------------------------
```
!
version 15.3
!
hostname TEST_ROUTER
!
snmp-server community test$#!@ RO 90
access-list 90 permit 10.0.0.10
```

Outputs:
---------------------------------------------------------------------------------
```
Summary: 0 (non-assertion) results; 
##############
# Undefined structures
Status: SUCCESS
Question: {
  "class" : "org.batfish.question.UndefinedReferencesQuestionPlugin$UndefinedReferencesQuestion",
  "differential" : false,
  "includeOneTableKeys" : false,
  "nodeRegex" : ".*"
}
TEST_ROUTER:
  ipv4 acl:
    !@ RO 90:
      snmp server community ipv4 acl: lines [6]

Summary: 4 (non-assertion) results; 
##############
# Unused structures
Status: SUCCESS
Question: {
  "class" : "org.batfish.question.UnusedStructuresQuestionPlugin$UnusedStructuresQuestion",
  "differential" : false,
  "includeOneTableKeys" : false,
  "nodeRegex" : ".*"
}
TEST_ROUTER:
  standard ipv4 access-list:
    90 lines [7]

```

**Comment by jlmcgraw** [comment]
I'm imagining the overall issue is what characters are allowed to be a part of names when parsing because I'm seeing a possibly related issue with prefix lists where the list is split into three separate elements because of the ":" in its name

# Inputs
!
version 15.1

router bgp 65000
 !
 neighbor 10.10.10.10 remote-as 65535
 neighbor 10.10.10.10 description eBGP peer
 neighbor 10.10.10.10 version 4
 !
 address-family ipv4
  neighbor 10.10.10.10 route-map SET_LOCALPREF200_eBGP in
 exit-address-family
!
ip bgp-community new-format
!
ip prefix-list SET_COMMUNITY_65535:200 seq 10 permit 10.0.0.0/8
!
ip prefix-list DEFINED_BUT_NOT_USED seq 10 permit 10.0.0.0/8
!
!
route-map SET_LOCALPREF200_eBGP permit 10
 match ip address prefix-list SET_COMMUNITY_65535:200
 set local-preference 200
 match ip address prefix-list USED_BUT_NOT_DEFINED
 set local-preference 50
!
end





# Outputs
Summary: 0 (non-assertion) results; 
############
# Undefined structures
Status: SUCCESS
Question: {
  "class" : "org.batfish.question.UndefinedReferencesQuestionPlugin$UndefinedReferencesQuestion",
  "differential" : false,
  "includeOneTableKeys" : false,
  "nodeRegex" : ".*"
}
test_router:
  ipv4 prefix-list:
    200:
      route-map match ipv4 prefix-list: lines [22]
    ::
      route-map match ipv4 prefix-list: lines [22]
    SET_COMMUNITY_65535:
      route-map match ipv4 prefix-list: lines [22]
    USED_BUT_NOT_DEFINED:
      route-map match ipv4 prefix-list: lines [24]

Summary: 4 (non-assertion) results; 
#############
# Unused structures
Status: SUCCESS
Question: {
  "class" : "org.batfish.question.UnusedStructuresQuestionPlugin$UnusedStructuresQuestion",
  "differential" : false,
  "includeOneTableKeys" : false,
  "nodeRegex" : ".*"
}
test_router:
  ipv4 prefix-list:
    DEFINED_BUT_NOT_USED lines [18]

**Comment by ratulm** [comment]
@arifogel - do you know whats happening here?

**Comment by arifogel** [comment]
The rule `variable_community_name` is used to parse the SNMP community string.
```
variable_community_name
:
   ~( NEWLINE | DOUBLE_QUOTE | GROUP | IPV4 | IPV6 | RO | RW | SDROWNER |
   SYSTEMOWNER | USE_ACL | USE_IPV4_ACL | USE_IPV6_ACL | VIEW )
;
```
This rule is executed in the default lexer mode. So essentially it will eat everything up (including whitespace, which is thrown out) until it hits one of the tokens listed in the negation  `~(...)`.

With only this information, you would think the problem does not occur. However, there is a complication:
```
POUND
:
   '#' -> pushMode ( M_Description )                                                                                                                                                                              
;
```

So after we hit the `#` character, we enter the `M_Description` lexer mode:
```
mode M_Description;                                                                                                                                                                                               

M_Description_NEWLINE
:
   F_Newline+ -> type ( NEWLINE ) , popMode
;

M_Description_NON_NEWLINE
:
   F_NonNewline+ -> type ( RAW_TEXT )
;
```
In this mode, everything - even whitespace - that is not a newline character is eaten up and tossed in a single `RAW_TEXT` token. So the community string that the parser sees is `test$#`, and the ACL it sees is`!@ RO 90`. This is because while the `variable_community_name` is greedy, it still cannot eat the last token. This is because without separating the last token (`RAW_TEXT`), there is no way to satisfy the `ss_community` rule:
```
ss_community
:
   COMMUNITY
   (
      name = variable_community_name
      |
      (
         DOUBLE_QUOTE name = variable_community_name DOUBLE_QUOTE
      )
   )
   (
      ssc_group
      | ssc_use_ipv4_acl
      | ssc_use_ipv6_acl
      | ssc_access_control
   )
;
```

The solution must involve changes to how `#` is treated. Otherwise, the `RO` - which forces termination of the community string - gets shoved in a `RAW_TEXT` token.

**Comment by arifogel** [comment]
I think if we don't expect to see `#` in the middle of a line in IOS, then we can put a semantic predicate in front of the `POUND` rule that disables it unless we are in IOS-XR where it is used for comments in a route-policy, etc.

**Comment by jlmcgraw** [comment]
So the issue with a “:” in a route map is a different issue all together?

**Comment by arifogel** [comment]
The relevant parser rule for `match ip address prefix-list` is:
```
match_ip_prefix_list_rm_stanza
:
   MATCH IP ADDRESS IP? PREFIX_LIST
   (
      name_list += variable
   )+ NEWLINE
;
```
Names of prefix-lists are parsed via the `variable` parser rule:
```
variable
:
   ~NEWLINE
;
```
Note that `variable` only consumes a single token. The tokens following the word `prefix-list` are likely to be: `VARIABLE`, `COLON`, `DEC`
So each of `SET_COMMUNITY_65535`, `:`, `200` is being treated as a reference to a prefix-list. The problem here is that we want only whitespace to be a prefix-list name boundary. This is not achievable with parser changes alone. At minimum we will also have to change the lexer to operate a bit differently for this line.
I will have to think a bit how to solve this without breaking a whole bunch of other stuff.

**Comment by arifogel** [comment]
The `!` in your snmp-server community string also created a problem, so I went a different route. See changes in #1923

**Comment by ratulm** [comment]
hey, @jlmcgraw - give it a shot and let us know if you see other issues. cheers.
