### ISSUE TITLE
Unimplemented match clauses - default strategy + implement

### ISSUE THREAD

**Issue by jlmcgraw** [batfish/batfish#1955]
Having "deny  ip any any fragments" as the first line in an IOS ACL causes the rest of the ACL to be considered unreachable

#### Example
```
ip access-list extended TEST
 remark ***DENY FRAGMENTS
 deny   ip any any fragments
 remark ***HOST***
 permit udp any host 10.0.0.1
 permit tcp any host 10.0.0.2
 deny udp any host 10.0.0.3
```

#### Output

```
Question: aclreachability aclNameRegex=".*" nodeRegex=".*"
Results for unreachable ACL lines

  HOST1 :: TEST
    [index 1] permit udp any host 10.0.0.1
      Earliest covering line: [index 0] deny   ip any any fragments
      Is different action: true
    [index 2] permit tcp any host 10.0.0.2
      Earliest covering line: [index 0] deny   ip any any fragments
      Is different action: true
    [index 3] permit udp any host 10.0.0.3
      Earliest covering line: [index 0] deny   ip any any fragments
      Is different action: false
```

**Comment by dhalperi** [comment]
@corinaminer can you take a look?

cc: @arifogel @anothermattbrown

**Comment by dhalperi** [comment]
My takeaways:

* the space of match clauses is pretty large across vendors, and it seems realistic that we're going to sometimes have some that are unimplemented. The default strategy then should be to make a line that isn't matchable, rather than simply ignoring those lines.
    if we assume that unimplemented correlated with "rarely reached in practice" -- e.g., like it does for fragmented packets -- this is probably a safe bet.

* we can implement fragment support, at least partially, pretty easily. we should do that.
