### ISSUE TITLE
BGP distribute-list out not modeled correctly

### ISSUE THREAD

**Issue by agember** [batfish/batfish#1970]
The attached [example configurations](https://github.com/batfish/batfish/files/2236387/configs.zip) demonstrate the problem.

The distribute-list out configured on r3 for neighbor 1.0.1.1 (r1) should prevent r3 from advertising 13.0.128.0/17 to r1.

However 13.0.128.0/17 is still advertised according to Batfish:
```
batfish> get bgpadvertisements
r1 EBGP_RECEIVED dstNode:r1 dstVrf:default dstIp:1.0.1.1 srcNode:r3 srcVrf:default srcIp:1.0.2.1 net:13.0.128.0/17 nhip:1.0.2.1 origin:IGP lp:100 med:0 weight:0 asPath:[[13]] communities:[] orIp:192.168.0.3 clst:[] srcProt:bgp
r3 EBGP_SENT dstNode:r1 dstVrf:default dstIp:1.0.1.1 srcNode:r3 srcVrf:default srcIp:1.0.2.1 net:13.0.128.0/17 nhip:1.0.2.1 origin:IGP lp:100 med:0 weight:-1 asPath:[[13]] communities:[] orIp:192.168.0.3 clst:[] srcProt:bgp
batfish> get routes
r1 vrf:default net:13.0.128.0/17 nhip:1.0.2.1 nhint:dynamic nhnode:r3 admin:20 cost:0 tag:none prot:bgp
```

A simulation using Cisco Virtual Internet Routing Lab shows the correct behavior:
```
r1#show ip route
Codes: L - local, C - connected, S - static, R - RIP, M - mobile, B - BGP
       D - EIGRP, EX - EIGRP external, O - OSPF, IA - OSPF inter area 
       N1 - OSPF NSSA external type 1, N2 - OSPF NSSA external type 2
       E1 - OSPF external type 1, E2 - OSPF external type 2
       i - IS-IS, su - IS-IS summary, L1 - IS-IS level-1, L2 - IS-IS level-2
       ia - IS-IS inter area, * - candidate default, U - per-user static route
       o - ODR, P - periodic downloaded static route, H - NHRP, l - LISP
       a - application route
       + - replicated route, % - next hop override, p - overrides from PfR

Gateway of last resort is not set

      1.0.0.0/8 is variably subnetted, 2 subnets, 2 masks
C        1.0.0.0/16 is directly connected, GigabitEthernet0/1
L        1.0.1.1/32 is directly connected, GigabitEthernet0/1
      3.0.0.0/8 is variably subnetted, 2 subnets, 2 masks
C        3.0.0.0/16 is directly connected, GigabitEthernet0/2
L        3.0.1.2/32 is directly connected, GigabitEthernet0/2
      11.0.0.0/8 is variably subnetted, 2 subnets, 2 masks
C        11.0.0.0/16 is directly connected, GigabitEthernet0/3
L        11.0.1.3/32 is directly connected, GigabitEthernet0/3
      12.0.0.0/16 is subnetted, 1 subnets
B        12.0.0.0 [20/0] via 3.0.2.1, 00:00:58
      13.0.0.0/17 is subnetted, 2 subnets
B        13.0.0.0 [20/0] via 1.0.2.1, 00:00:58
B        13.0.128.0 [20/0] via 3.0.2.1, 00:00:27
      192.168.0.0/32 is subnetted, 1 subnets
C        192.168.0.1 is directly connected, Loopback0
r1#show bgp
BGP table version is 5, local router ID is 192.168.0.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal, 
              r RIB-failure, S Stale, m multipath, b backup-path, f RT-Filter, 
              x best-external, a additional-path, c RIB-compressed, 
              t secondary path, 
Origin codes: i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>   11.0.0.0/16      0.0.0.0                  0         32768 i
 *    12.0.0.0/16      1.0.2.1                                0 13 12 i
 *>                    3.0.2.1                  0             0 12 i
 *    13.0.0.0/17      3.0.2.1                                0 12 13 i
 *>                    1.0.2.1                  0             0 13 i
 *>   13.0.128.0/17    3.0.2.1                                0 12 13 i
```

**Comment by progwriter** [comment]
@agember You are absolutely correct, currently batfish does not support distribute lists with BGP. I'll look into what's required for that support.

**Comment by aaglenn** [comment]
@progwriter did you have any notes to share on what is needed to support distribute lists? I have a potential upcoming need for this functionality and I'm not opposed to making an attempt at implementing it.

**Comment by progwriter** [comment]
@aaglenn Sure, there are a few steps involved to ensure full end-to-end support (links are to potential code entry points).
1. Parsing support. [Starting point](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/grammar/cisco/CiscoControlPlaneExtractor.java#L4893)
2. [Conversion](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/representation/cisco/CiscoConfiguration.java#L1794) to vendor independent model, such that referenced lists are tracked at the [neighbor/BgpPeerConfig](https://github.com/batfish/batfish/blob/master/projects/batfish-common-protocol/src/main/java/org/batfish/datamodel/BgpPeerConfig.java) level 
3. Dataplane engine support, so that referenced lists are processed upon [import](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L1633) and [export](https://github.com/batfish/batfish/blob/master/projects/batfish/src/main/java/org/batfish/dataplane/ibdp/VirtualRouter.java#L3098)

Hope that helps, feel free to reach out with further questions on github/slack

**Comment by corinaminer** [comment]
Added support for neighbor-specific distribute-lists in #3578. Tested with @agember's example network. r3 has stopped advertising `13.0.128.0/17` to r1, and r1's routes match up with the `show bgp` output above.

Thanks for sharing configs, hope this helps!
