### ISSUE TITLE
Support Cisco "no nameif"

### ISSUE THREAD

**Issue by plannigan** [batfish/batfish#2174]
The Cisco interface grammar supports a large "no xxx" settings, but is missing 

    no nameif

This causes the following to not be properly parsed

```
interface GigabitEthernet0/3
 shutdown
 no nameif
 no security-level
 no ip address
```

**Comment by dhalperi** [comment]
Hey @plannigan - thanks! Parsing support is easy to add (Cisco ASA I presume?) -- we do it mostly on demand -- will send a PR in a bit.

Batfish warns that this line is unrecognized, but it should actually recover just fine afterwards at the next top-level stanza. Since the interface is shutdown, I wouldn't expect this to affect any of your analyses.

Are you seeing any strong behavioral differences?

**Comment by plannigan** [comment]
Yes, this was found as a result of looking into Cisco ASA. Wasn't causing any problems, but it was as simple thing that would be easy to address. I'm tracking down some other things that will require some more code.

**Comment by dhalperi** [comment]
:+1:
