### ISSUE TITLE
FileParseStatus - does not reflect new nodes created from logical systems

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#2745]

**Comment by arifogel** [comment]
Is this still an issue? Which question exactly are we referring to?

**Comment by dhalperi** [comment]
The FileParseStatus question. Yes.

**Comment by arifogel** [comment]
Right now the `FileParseStatusAnswerer` gets all of its input from the `ParseVendorConfigurationAnswerElement`. Strictly speaking, logical systems are not known until after conversion. Unfortunately, the `ConvertConfigurationAnswerElement` does not record which nodes came from which files.

Proposed solution:
- Add mapping from `hostname -> srcFiles` (will be one source file in most cases) to `ConvertConfigurationAnswerElement`. This can be partially populated by caller of `VendorConfiguration.toVendorConfigurations`.
- Have `FileParseStatusAnswerer` join `hostname -> srcFiles` information from `ConvertConfigurationAnswerElement`with existing information extracted from `ParseVendorConfigurationAnswerElement` so that `Nodes` column can be appropriately populated with all nodes produced from a given file.
