### ISSUE TITLE
searchFilters: Inverse Searching with Multiple Headers

### ISSUE THREAD

**Issue by supertylerc** [batfish/batfish#4314]
Similar to #4147.

The use case is basically something like this:

A security team wants to define a pre-set list of "acceptable flows" for an ACL (or multiple ACLs).  They want to enable others to submit ACL changes, and so long as those changes are within the list of "acceptable flows", then no security review is opened and the ACL can be merged automatically.  However, if someone submits a pull request to update an ACL, and that change violates the list of "acceptable flows," then it triggers a security review.  If the flow is determined to be legitimate, then the security engineer can update the tests to permit exactly that flow, and the pull request can re-run tests and be merged after passing.

More context is available in the Batfish Slack starting [here](https://batfish-org.slack.com/archives/C8XKQNHAQ/p1563840367005900).

**Comment by ratulm** [comment]
@anothermattbrown - what is your view of Batfish being able to support this?

**Comment by dhalperi** [comment]
The solution is (still) to move off of top level invert search and into
proper AST I think

**Comment by anothermattbrown** [comment]
I agree with Dan, `invertSearch` is too limited. It would be better to generalize from a single HeaderConstraints object to an AST including HeaderConstraints at the leaves, and AND, OR, and NOT operators.

In the meantime, we can support this use case using differential [`searchFilters`](https://pybatfish.readthedocs.io/en/latest/questions.html#pybatfish.question.bfq.searchFilters) and/or [`compareFilters`](https://pybatfish.readthedocs.io/en/latest/questions.html#pybatfish.question.bfq.compareFilters). We can create a new snapshot `ACCEPTABLE_FLOWS_SNAPSHOT` containing the ACLs defining the acceptable flows of the network ACL. Then if we use `ACCEPTABLE_FLOWS_SNAPSHOT` as the reference in differential `searchFilters`, an increased result will be an unacceptable flow permitted by the network ACL (i.e. permitted by the network ACL but denied by the acceptable flows ACL). Similarly, if we use `compareFilters`, the answer will include the lines of the network ACL that permit unacceptable flows. Each line will be matched with the line(s) where the flows are denied in the acceptable flows ACL.

In fact, this may be easier for some users, since they can specify complex headerspaces in a familiar ACL syntax instead of using a complex HeaderConstraints AST. It should be easy to work up a pure-pybatfish solution using [`init_snapshot_from_text`](https://pybatfish.readthedocs.io/en/latest/api.html?highlight=init_snapshot_from_acl#pybatfish.client.session.Session.init_snapshot_from_text).

**Comment by ratulm** [comment]
hey, @supertylerc - does the method suggested by Matt make sense and usable for you? if so, one of us can share python snippets to how exactly how it can be realized.

**Comment by supertylerc** [comment]
@ratulm yeah, I think I can probably figure something out.  Thank you!

**Comment by anothermattbrown** [comment]
@supertylerc Here's an example notebook demonstrating the idea.
[example.zip](https://github.com/batfish/batfish/files/3427827/example.zip)
