### ISSUE TITLE
Provide some guidance on minumum machine requirements to compile and/or run

### ISSUE THREAD

**Issue by jlmcgraw** [batfish/batfish#501]
I've had problems getting batfish to compile with the Linux virtual machines I have access to, which are limited to 2-3GB of RAM.

Via various combinations of increasing java memory allocations using:
  
export JAVA_OPTS="-Xms1536m -Xmx2048m"

I've gotten it to succeed once but haven't had luck since

What do you consider the minimum requirements for compiling/running Batfish?

Errors look like:
[INFO] Compiling 605 source files to /home/jlmcgraw/Documents/github/batfish/projects/batfish/target/classes

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space

**Comment by ratulm** [comment]
@jlmcgraw, a broad guidance is hard to provide because it all depends on the size of the network or complexity of the policies in it. most of us developers run on (bare metal) computers with 16-32 GB of RAM which is sufficient for most use cases. i used to run on a 8 GB computer which also worked well for the example networks in the repository.

How big is the network that you are trying on?

**Comment by jlmcgraw** [comment]
I’m actually just tying to compile it reliably, I haven’t gotten to the
point of doing any analysis with it yet.

Unfortunately my current machine has only 4GB so any virtual machines I run
on it are limited to less

This is using Ubuntu 1704 and its associated openjdk packages (v8 I
believe?)

**Comment by ratulm** [comment]
In case this helps: on my MacBook, openjdk peaked at 2.5 GB while compiling from scratch.

So, with the memory footprint of the OS, 4GB is cutting it quite close I believe, which might explain what you are seeing.

**Comment by ratulm** [comment]
@jlmcgraw did this issue get resolved? I am closing the ticket for now, but feel free to reopen if you are still having issues.
