### ISSUE TITLE
Static route missing from BGP advertisement

### ISSUE THREAD

**Issue by jgeromero** [batfish/batfish#5071]
Hi,

I have the following static route (Junos):
` set routing-instances shared-inside routing-options static route 10.7.57.0/24 qualified-next-hop ams30.20
set routing-instances shared-inside routing-options static route 10.7.57.0/24 preference 170 `

However, my BGP peer never learns it and batfish is not seeing static route installed, using the following question to verify:

`routes_bgp = routes_all[(routes_all['Node'].str.contains('iad0-router')) & (routes_all['VRF'] == 'shared-inside') & (routes_all['Protocol'] == 'static')]
routes_bgp `

I was told this may be related to the lack of parsing support using qualified next hops. Can someone please confirm? Thank you.

**Comment by dhalperi** [comment]
@haverma is working on this. Sounds like a bunch of context has been shared on Slack.

**Comment by haverma** [comment]
Thanks @jgeromero for reporting this ! This was indeed because of lack of parsing support of qualified next hops. 
Support was added in https://github.com/batfish/batfish/pull/5088 and you can use the current master branch of batfish to try it and it will also be available in our next batfish release.
