### ISSUE TITLE
compareFilters with two different nodes config files with same Filter name

### ISSUE THREAD

**Issue by nitinics** [batfish/batfish#5314]
I could use compareFilters to compare filters between two snapshots with same filter name, when I paste the ACL under text via `init_snapshot_from_text` 

However, when I use the entire router config data for two snapshots with init_snapshot_from_text .. two different node configs with same ACL name .. the compareFilters returns nothing. I can validate that filterLineReachability works per snapshot/per node config.

Is this expected? If so - how do I compare two different nodes configuration with same filter name.

**Comment by ratulm** [comment]
hey, @nitinics - comparing filters across nodes is not supported out of the box; batfish questions are geared toward comparing similar things across snapshots. 

can you say a bit more about use case? we might be able to suggest a workaround or consider adding that capability in the future.

**Comment by nitinics** [comment]
So - I have 2 redundant nodes within a snapshot that have redundancy config elements (including acls, route-maps etc). It would be nice to compare filters between two nodes for consistency/compliance checks, including reasoning.

I was able to make it work with two snapshots with `init_snapshot_from_text` with only the text portion of the acl and using compareFilters. 

However, when I do the same with loading two snapshots each with the entire config of the two nodes into `init_snapshot_from_text` - it doesn't work.

**Comment by ratulm** [comment]
It does not work in the second case (with full file content) likely because batfish is inferring different hostnames for the two nodes, that is, you get hostname=node1 in the first snapshot and hostname=node2 in the second snapshot. These hostnames are picked from the file content (https://pybatfish.readthedocs.io/en/latest/api.html#pybatfish.client.session.Session.init_snapshot_from_text). You can confirm my hypothesis using the nodeProperties question, which will list all hosts in a snapshot. 

If that is what is happening, you probably need to manipulate the config text such that they both have the same hostnames, and then you'd be able to compare identically named filters across the two.

**Comment by nitinics** [comment]
@ratulm That was it. I actually removed the hostname from the two files to do comparison and it took the default. Thanks for your help
