### ISSUE TITLE
Document intended way to interact with batfish programmatically

### ISSUE THREAD

**Issue by virtuald** [batfish/batfish#599]
Interacting with batfish from interactively seems fairly well defined for simple use cases -- start allinone, execute text commands. However, it's not clear how one is intended to control batfish in a programmatic manner.

Looking at the client, it uses `BfCoordWorkHelper` to communicate with the other pieces of batfish, and this seems to be the way to go -- except! There's quite a bit of logic that still resides in Client that would be useful for a program to use. For example, `uploadTestrig` or the various `answer` functions. Unfortunately, all of those methods are private, so it seems like they aren't intended to be used externally.

Another approach is to just create a client object and send it commands directly via `run`, but this seems potentially error prone, and it seems to be difficult for a controlling program to determine the internal state of batfish if one went that route.

**Comment by ratulm** [comment]
Hey, @virtuald, the "design intent" was the first approach that you are suggesting: all (Java) clients would use `BfCoordWorkHelper` to develop their functionality. Most of what the current `Client` is doing is parsing the command lines and executing with the help of `BfCoordWorkHelper.` 

If you look at `uploadTestrig,` it is only getting the inputs into shape because the `Client` supports both directories and zips as inputs, and it then calls `BfCoordWorkHelper.uploadTestrig` to get the job done.  Similarly, the various `answer` series are for the different types of inputs that the client accepts. 

If there is functionality in `Client` that you think is generally useful for other (Java) clients,  we can push that to another utility class or `BfCoordWorkHelper`. Feel free to suggest concrete changes on that front.

**Comment by virtuald** [comment]
It seems to me that `BfCoordWorkHelper` is a 'low level' API that isn't really suitable for 'casual' programmatic interaction. In particular, there seems to be a separation between simple commands and longer running things that require a work item.

I think a casual API user would rather have some object that essentially mimics all of the commands available to interactive users -- and perhaps that's a naive wish, but it seems easier to grok since everything a casual user is going to know about batfish are the things that they experience with the interactive allinone console. The simple commands that are available in `BfCoordWorkHelper` are fine, but anything that requires a work item seems to have a lot of additional packaging logic associated with it. Additionally, it seems nice to be able to say 'setContainer' and then not have to worry about passing it to every. single. call... but once again, perhaps that's a naive wish.

For now, I have a tight deadline to meet, so I think I'm just going to use processCommand() and see where that gets me.
