### ISSUE TITLE
question about Adding parsing for a new vendor

### ISSUE THREAD

**Issue by tuyu95** [batfish/batfish#6376]
Hi,
I've read the 'Adding parsing for a new vendor' part on https://github.com/batfish/batfish/wiki/Developer-notes#adding-parsing-for-a-new-vendor, and the 'New Parser Notes'. After that, I have a question:
In 'New Parser Notes', there is no step about compile; and in  'Adding parsing for a new vendor', compile is at step 3. Is it necessary to compile again after step 7 (or, after all the changes)?
Thanks, and happy Halloween!

**Comment by ratulm** [comment]
Yes, you'll need to compile again after step 7 (and any incremental change after that).

The reason compile is mentioned explicitly after step 3 is because that is needed to populate the symbols you'll need for Step 4. In general, after any grammar (.g4) changes, compile before making additional java changes. 

Happy Halloween!
