### ISSUE TITLE
Question about reachability

### ISSUE THREAD

**Issue by EvgeniNetformx** [batfish/batfish#7011]
Dear Batfish team.

[LabNextTestV2.zip](https://github.com/batfish/batfish/files/6514065/LabNextTestV2.zip)

We invoked 
 result=bfq.reachability( headers=HeaderConstraints(srcIps='10.62.62.3', dstIps='10.60.60.4', ipProtocols='TCP'), actions='success').answer().frame() for the attached input and got many traces in the results that are doesn't start from 10.62.62.3.

Can you please advise why does it happen?

Thanks.

**Comment by ratulm** [comment]
Do the traces start on the same node where `10.62.62.3` is? 

PS: Our Slack channel is a better place to ask such questions. You'll likely get faster responses and that supports back-n-forth if needed. As you see, my answer to your question is a question :)

**Comment by EvgeniNetformx** [comment]
Dear Batfish engineer.

Thanks for the response.

1) Whether criteria headers=HeaderConstraints(srcIps='10.62.62.3'.. )assumes that the address of the first node in trace will be 10.62.62.3?

Please provide link or email for Batfish  Slack channel.

Thanks.

**Comment by ratulm** [comment]
https://join.slack.com/t/batfish-org/shared_invite/enQtMzA0Nzg2OTAzNzQ1LTcyYzY3M2Q0NWUyYTRhYjdlM2IzYzRhZGU1NWFlNGU2MzlhNDY3OTJmMDIyMjQzYmRlNjhkMTRjNWIwNTUwNTQ

**Comment by corinaminer** [comment]
Hi @EvgeniNetformx, I took a look at your reachability query on that snapshot, and I'm seeing only traces with source IP `10.62.62.3`. However, it's true that those traces start at various places in the network. Please note that the `headers` parameter strictly limits the simulated packet itself, not its path.

If you want to limit your search to a specific starting point, you can specify `startLocation` in the `pathConstraints` parameter (docs [here](https://pybatfish.readthedocs.io/en/latest/datamodel.html#pybatfish.datamodel.flow.PathConstraints)). The `startLocation` is a location specifier string, whose grammar is documented [here](https://pybatfish.readthedocs.io/en/latest/specifiers.html#location-specifier). As an example, if you only want to find flows that match your original query and also originate on node `pca`, you can do:
```
headers = HeaderConstraints(srcIps='10.62.62.3', dstIps='10.60.60.4', ipProtocols='TCP')
path = PathConstraints(startLocation='pca')
result = bfq.reachability(headers=headers, pathConstraints=path, actions='success').answer().frame()
```

Hope that helps. Feel free to ask further questions here or on Slack.

**Comment by eyal773** [comment]
@corinaminer Thanks for your useful response.
So, in that case, the meaning of the  HeaderConstraints parameter **srcIps**, and what happens if we leave it empty?

**Comment by corinaminer** [comment]
Hi @eyal773. Generally, if `srcIps` is not specified in `HeaderConstraints`, that means there is no constraint on the packet's source IPs. However, when `srcIps` isn't specified, the reachability query does implicitly limit source IPs based on where each flow starts. Here are the details from [location specifier documentation](https://pybatfish.readthedocs.io/en/latest/specifiers.html#location-specifier):
> Unless explicitly specified, questions like traceroute and reachability will automatically assign IP addresses to packets based on their location. For InterfaceLocation, the set of assigned addresses is the interface address(es). This set is empty for interfaces that do not have an assigned address. For InterfaceLinkLocation, the set of assigned addresses corresponds to what (hypothetical) hosts attached to that interface can have, which includes all addresses in the subnet except for the address of the interface and the first and last addresses of the subnet. This set is empty for interface subnets that are /30 or longer (e.g., loopback interfaces).

One tip you may find useful, since you're asking about less-constrained inputs: The reachability query is especially powerful for proving something *cannot* happen. For example, suppose you wanted to prove that no TCP packets can successfully reach device D1. Then you can run a reachability query searching for *any successful* TCP traffic to D1:
```
tcp_headers = HeaderConstraints(ipProtocols='TCP')
end_at_d1 = PathConstraints(endLocation='D1')
bfq.reachability(headers=tcp_headers, pathConstraints=end_at_d1, actions='success').answer().frame()
```
If any TCP packet can reach D1 successfully from anywhere, this query will find that flow, so if this query yields *no* results, then you've proved no TCP traffic can reach D1. The same principle can be used for proving *all* specified traffic can reach somewhere, by setting `actions='failure'` and getting no results (therefore no failing flows, therefore all flows succeed).
