### ISSUE TITLE
TestrigMetadataService doesn't handle old testrigs

### ISSUE THREAD

**Issue by dhalperi** [batfish/batfish#785]
if you ask a question on a testrig that existed before #741 , you get a null pointer exception.

Testrig metadata should be recomputed if it does not exist.

**Comment by ratulm** [comment]
This issue is for backwards compatibility? Doing such a thing would require
writing logic that requires coordinator to peek inside the testrig and its
files to determine the status of the testrig (one of seven --
uninitialized, parsing_fail, parsing, parsed, dataplaning,
dataplaning_fail, dataplaned) based on state of the files there. This would
be brittle unless we change batfish workers to dump the status clearly.
Worth the effort?  (going forward, all testrigs should have the metadata.)

**Comment by dhalperi** [comment]
In this case, may not be worth the effort. But as usage grows we need to make backwards compatibility a priority.

This issue can serve as explanation when others are also broken on upgrade.
