### ISSUE TITLE
FRR: not announcing learned iBGP routes over eBGP

### ISSUE THREAD

**Issue by xythrez** [batfish/batfish#8588]
**Describe the bug**
Cumulus/FRR configs not announcing learned iBGP routes over eBGP: In the attached FRR configs, Learned ibgp route `10.2.10.0/24` in `s1`'s RIB does not show up in the RIB of its eBGP neighbor `s0`, despite no policy blocking it.

**Expected behavior**
The RIB of `s0` should include a route for `10.2.10.0/24` when the route is not blocked by a policy.

**Runnable example**
```py
from pybatfish.client.session import Session

session = Session(host='localhost')
session.set_network('test_network')
session.init_snapshot('frr_bgp/', overwrite=True)

print(session.q.initIssues().answer().frame())
print(session.q.fileParseStatus().answer().frame())
print(session.q.bgpRib(nodes='s0', network='10.2.10.0/24').answer().frame())
```

**Topology**
There are three switches (`s0`, `s1`, `s2`) and one host (`d1`). `s0` and `s1` are connected via eBGP, `s1` and `s2` are connected via iBGP. `d1` is connected to `s2`. Prefix `10.2.10.0/24` is provided by `s2`.

**Snapshots included as attachments**
- [frr_bgp.zip](https://github.com/batfish/batfish/files/9985018/frr_bgp.zip): Hand written configs for Cumulus/FRR. Exhibits bugged behavior.
- [cisco_bgp.zip](https://github.com/batfish/batfish/files/9985019/cisco_bgp.zip): Same as `frr_bgp` but in Cisco config format. Exhibits expected behavior.

**Comment by arifogel** [comment]
In the FRR snapshot, I don't see any such iBGP route on s1, so at first glance there is nothing to forward over eBGP:
![image](https://user-images.githubusercontent.com/7737874/203266874-c074c53c-c521-4ab7-ad40-f2b6a5aa316f.png)

Looks like the OSPF route for that network is taking priority due to lower admin distance

In the cisco snapshot, that route is also OSPF on s1. It is advertised regardless because by default, IOS advertises inactive routes unless you use `bgp suppress-inactive`.

I can't find a similar command on FRR, and I'm not sure what the default behavior is for advertising inactive routes. Can you confirm that you've tested this on an actual FRR device in lab, and Batfish is doing the wrong thing?

**Comment by xythrez** [comment]
Sorry for the delay, here's the RIB and BGP RIB on Cumulus Linux 5.2.0 via NVIDIA Air, both of which include the missing prefix 10.2.10.1/24:

![Screenshot_20221127_194555](https://user-images.githubusercontent.com/46275090/204189957-6990f131-1806-4506-9cf3-edbd366e40a7.png)
