### ISSUE TITLE
[Cisco IOS] Cisco interface grammar limits number of standby_group up to 255

### ISSUE THREAD

**Issue by pawelhaj** [batfish/batfish#8607]
Hello,

In HSRP version 1, group numbers are restricted to the range from 0 to 255. 
HSRP version 2 expands the group number range from 0 to 4095.

Current grammar definition  (Cisco_interface.g4) limits group number to uint8.
```
(...)
standby_group
:
  group = uint8
  (
    standby_group_authentication
    | standby_group_ip
    | standby_group_preempt
    | standby_group_priority
    | standby_group_timers
    | standby_group_track
  )
;
```
For the  following configuration error is returned: 
_Parse warning, This syntax is unrecognized [if_standby if_inner s_interface_definition s_interface stanza cisco_configuration]_

```
interface Vlan521
 ip address 126.198.1.2 255.255.255.192
 standby version 2
 standby 521 ip 126.198.1.1
 standby 521 timers msec 500 3
 standby 521 priority 105
 standby 521 preempt
 standby 521 track 1 decrement 10
!
```

**Comment by pawelhaj** [comment]
Does anyone confirm that standby_group should accept values greater than uint8 (255) ?

**Comment by arifogel** [comment]
@pawelhaj thanks for filing this, and I apologize for the long delay.

I'm including the below for visibility:
The higher limit for HSRP version 2 is noted in this Cisco [HSRP Version 2 doc](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ipapp_fhrp/configuration/15-mt/fhp-15-mt-book/fhp-hsrp-v2.pdf)

In order to use numbers above 255, you must declare `standby version 2` as in the example provided by @pawelhaj.
